import type { Order } from "@/types";

export const MOCK_ORDERS: Order[] = [
  {
    id: "ORD-001",
    customerName: "Sarah Mitchell",
    customerEmail: "sarah@example.com",
    amount: 29.99,
    status: "delivered",
    paymentMethod: "card",
    createdAt: "2024-12-01T10:30:00Z",
    downloadToken: "tok_abc123",
  },
  {
    id: "ORD-002",
    customerName: "James Chen",
    customerEmail: "james@example.com",
    amount: 29.99,
    status: "paid",
    paymentMethod: "crypto",
    createdAt: "2024-12-02T14:15:00Z",
    downloadToken: "tok_def456",
  },
  {
    id: "ORD-003",
    customerName: "Emma Rodriguez",
    customerEmail: "emma@example.com",
    amount: 29.99,
    status: "pending",
    paymentMethod: "click",
    createdAt: "2024-12-03T09:00:00Z",
  },
  {
    id: "ORD-004",
    customerName: "Michael Brooks",
    customerEmail: "michael@example.com",
    amount: 29.99,
    status: "delivered",
    paymentMethod: "payme",
    createdAt: "2024-12-04T16:45:00Z",
    downloadToken: "tok_ghi789",
  },
  {
    id: "ORD-005",
    customerName: "Lisa Wang",
    customerEmail: "lisa@example.com",
    amount: 29.99,
    status: "refunded",
    paymentMethod: "card",
    createdAt: "2024-12-05T11:20:00Z",
  },
  {
    id: "ORD-006",
    customerName: "Ahmed Karimov",
    customerEmail: "ahmed@example.com",
    amount: 29.99,
    status: "paid",
    paymentMethod: "click",
    createdAt: "2024-12-06T08:30:00Z",
  },
  {
    id: "ORD-007",
    customerName: "Dilnoza Yusupova",
    customerEmail: "dilnoza@example.com",
    amount: 29.99,
    status: "delivered",
    paymentMethod: "payme",
    createdAt: "2024-12-07T13:00:00Z",
    downloadToken: "tok_jkl012",
  },
  {
    id: "ORD-008",
    customerName: "Bob Johnson",
    customerEmail: "bob@example.com",
    amount: 29.99,
    status: "pending",
    paymentMethod: "crypto",
    createdAt: "2024-12-08T17:30:00Z",
  },
];
